local RSGCore = exports['rsg-core']:GetCoreObject()

RSGCore.Functions.CreateUseableItem("smallbackpack", function(source, item)
    local Player = RSGCore.Functions.GetPlayer(source)
    TriggerClientEvent('rsg-Backpack:Client:Smallbackpack', source, item.info.smallbackpackid)
end)
RSGCore.Functions.CreateUseableItem("mediumbackpack", function(source, item)
    local Player = RSGCore.Functions.GetPlayer(source)
    TriggerClientEvent('rsg-Backpack:Client:Mediumbackpack', source, item.info.mediumbackpackid)
end)
RSGCore.Functions.CreateUseableItem("largebackpack", function(source, item)
    local Player = RSGCore.Functions.GetPlayer(source)
    TriggerClientEvent('rsg-Backpack:Client:Largebackpack', source, item.info.largebackpackid)
end)